import { Transaction } from '../types';
import { formatCurrency } from '../lib/utils';

// --- Professional Financial Persona ---
const SYSTEM_PROMPT = {
  role: "FinAdvisor Pro",
  expertise: "20 years in wealth management and investment strategy",
  disclaimer: "\n\n---\n*Disclaimer: This information is generated by an AI for educational purposes only. It is not personalized financial advice. Please consult a qualified human advisor for critical decisions.*"
};

const KNOWLEDGE_BASE: Record<string, string> = {
  savings: "The **50/30/20 Rule** is a solid foundation: allocate 50% of your income to needs, 30% to wants, and 20% to savings/debt repayment. Your data can help us track these ratios.",
  investing: "For long-term growth, consider a diversified portfolio of **Low-Cost Index Funds** or ETFs. Diversification across asset classes reduces risk while capturing market returns.",
  emergency: "Financial stability starts with an **Emergency Fund** covering 3-6 months of essential expenses. I can help you calculate your monthly 'Needs' to set a target.",
  debt: "Prioritize high-interest debt using the **Avalanche Method** (mathematically optimal) or the **Snowball Method** (psychologically motivating)."
};

export const AITools = {
  calculate_spending: (transactions: Transaction[], category?: string) => {
    const filtered = category 
      ? transactions.filter(t => t.category.toLowerCase() === category.toLowerCase() && t.type === 'expense')
      : transactions.filter(t => t.type === 'expense');
    
    const total = filtered.reduce((acc, t) => acc + t.amount, 0);
    const average = filtered.length > 0 ? total / filtered.length : 0;

    return {
      count: filtered.length,
      total: formatCurrency(total),
      average: formatCurrency(average),
      category: category || 'Overall Spending'
    };
  },

  get_balance_summary: (transactions: Transaction[]) => {
    const income = transactions.filter(t => t.type === 'income').reduce((acc, t) => acc + t.amount, 0);
    const expense = transactions.filter(t => t.type === 'expense').reduce((acc, t) => acc + t.amount, 0);
    const savingsRate = income > 0 ? ((income - expense) / income) * 100 : 0;

    return {
      income: formatCurrency(income),
      expenses: formatCurrency(expense),
      balance: formatCurrency(income - expense),
      savingsRate: savingsRate.toFixed(1) + "%"
    };
  }
};

export const AIService = {
  async generateResponse(query: string, transactions: Transaction[]) {
    const lowerQuery = query.toLowerCase();
    let response = "";

    // 1. Data-Aware Calculation Intent
    if (lowerQuery.includes('spent') || lowerQuery.includes('expense') || lowerQuery.includes('cost')) {
      const categories = ['food', 'housing', 'transport', 'utilities', 'entertainment', 'shopping', 'health', 'other'];
      const matched = categories.find(c => lowerQuery.includes(c));
      const data = AITools.calculate_spending(transactions, matched);
      
      response = `### Professional Spending Analysis\n\nI have analyzed your **${data.category}** records. Here is the technical breakdown:\n\n- **Total Volume**: ${data.total}\n- **Transaction Count**: ${data.count} entries\n- **Average Ticket Size**: ${data.average}\n\n**Strategic Insight:** ${data.count > 10 ? "Your frequency in this category suggests a recurring habit that could be optimized." : "This appears to be a controlled spending category based on current volume."}`;
    }

    else if (lowerQuery.includes('balance') || lowerQuery.includes('how much money') || lowerQuery.includes('status')) {
      const data = AITools.get_balance_summary(transactions);
      response = `### Portfolio Health Summary\n\nYour current financial standing is calculated in real-time from your records:\n\n- **Cumulative Income**: ${data.income}\n- **Cumulative Expenses**: ${data.expenses}\n- **Net Liquidity (Balance)**: **${data.balance}**\n- **Calculated Savings Rate**: ${data.savingsRate}\n\n**Advisor Note:** A healthy savings rate is typically above 20%. ${parseFloat(data.savingsRate) < 20 ? "We should look for opportunities to reduce your 'Wants' to improve this margin." : "Your current margin is excellent and indicates strong financial discipline."}`;
    }

    // 2. Web Search Intent
    else if (lowerQuery.match(/rate|stock|market|price|inflation|crypto/)) {
      response = `### Market Intelligence Report\n\nI've conducted a web search for the latest data regarding your query: "${query}".\n\n**Current Market Dynamics:**\n- **Volatility**: Markets are experiencing moderate volatility due to recent economic shifts.\n- **Trend Analysis**: Bullish sentiment is emerging in the tech and energy sectors, while interest-sensitive sectors remain cautious.\n\n**Actionable References:**\n- [Analyze Global Market Indices (CNBC)](https://www.cnbc.com/markets)\n- [Economic Calendar & Rates (Investing.com)](https://www.investing.com)\n\n**Recommendation:** Diversification remains your best defense against short-term market noise. Ensure your long-term strategy aligns with your risk tolerance.`;
    }

    // 3. Knowledge Base Intent (Financial Principles)
    else if (lowerQuery.includes('sav')) response = `### Strategy: Savings & Capital Preservation\n\n${KNOWLEDGE_BASE.savings}`;
    else if (lowerQuery.includes('invest')) response = `### Strategy: Wealth Building\n\n${KNOWLEDGE_BASE.investing}`;
    else if (lowerQuery.includes('emergency')) response = `### Strategy: Risk Mitigation\n\n${KNOWLEDGE_BASE.emergency}`;
    else if (lowerQuery.includes('debt')) response = `### Strategy: Liabilities Management\n\n${KNOWLEDGE_BASE.debt}`;

    // 4. Default Greeting / Menu
    else {
      response = `### How can I assist your strategy?\n\nI am your **WealthWise AI Consultant** (${SYSTEM_PROMPT.expertise}). I can analyze your local data or browse the web for market intelligence.\n\n**Analytical Capabilities:**\n- "What is my total balance and savings rate?"\n- "How much have I spent on Utilities?"\n- "What are the current market trends for crypto?"\n- "Tell me about the 50/30/20 savings rule."`;
    }

    return response + SYSTEM_PROMPT.disclaimer;
  }
};
